<a href="https://colab.research.google.com/github/shreyasvinaya/SAiDL-Summer-Assignment-2023/blob/main/SAIDL_assignment_task2_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!wget https://hasocfire.github.io/hasoc/2019/files/hindi_dataset.zip
!unzip hindi_dataset.zip

--2023-07-19 19:21:07--  https://hasocfire.github.io/hasoc/2019/files/hindi_dataset.zip
Resolving hasocfire.github.io (hasocfire.github.io)... 185.199.110.153, 185.199.109.153, 185.199.108.153, ...
Connecting to hasocfire.github.io (hasocfire.github.io)|185.199.110.153|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 667717 (652K) [application/zip]
Saving to: ‘hindi_dataset.zip’

hindi_dataset.zip   100%[===================>] 652.07K  --.-KB/s    in 0.03s   

2023-07-19 19:21:07 (23.2 MB/s) - ‘hindi_dataset.zip’ saved [667717/667717]

Archive:  hindi_dataset.zip
   creating: hindi_dataset/
  inflating: __MACOSX/._hindi_dataset  
  inflating: hindi_dataset/hindi_dataset.tsv  
  inflating: __MACOSX/hindi_dataset/._hindi_dataset.tsv  
  inflating: hindi_dataset/hasoc2019_hi_test_gold_2919.tsv  
  inflating: __MACOSX/hindi_dataset/._hasoc2019_hi_test_gold_2919.tsv  


In [ ]:
!pip install -q transformers==4.28.0
!pip install googletrans==4.0.0rc1


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 22.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 30.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 55.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.1/55.1 kB 2.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 7.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.4/133.4 kB 14.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 8.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 5.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.6/53.6 kB 7.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.0/65.0 kB 8.7 MB/s eta 0:00:00
  Created wheel for googletrans: filename=googletrans-4.0.0rc1-py3-none-any.whl size=17397 sha256=735a5233c6b7ae3cfc464fabb5fb7e46948f2d11a5e695b6aa07ab0c044df3d

In [ ]:
import pandas as pd
import random
from googletrans import Translator
from transformers import BertTokenizer, BertForSequenceClassification, MBartForConditionalGeneration, MBart50TokenizerFast, Trainer, TrainingArguments
import torch
from sklearn.metrics import accuracy_score


In [ ]:
import pandas as pd
import re

# Load HASOC 2019 Hindi dataset
data = pd.read_csv("/content/hindi_dataset/hindi_dataset.tsv", sep = '\t')

# Data cleaning function
def clean_text(text):
    # Remove special characters, URLs, and irrelevant information
    text = re.sub(r"http\S+|www\S+|https\S+", "", text, flags=re.MULTILINE)

    text = re.sub(r'@\S+', '', text)
    text = re.sub(r'#\S+', '', text)
    text = text.strip()

    return text

# Clean the dataset
data["cleaned_text"] = data["text"].apply(clean_text)



In [ ]:
data_tasks = pd.get_dummies(data[['task_1', 'task_2', 'task_3']])
data = data[['text_id', 'text']]
# concatenate the text and task DataFrames
data = pd.concat([data, data_tasks], axis=1)


In [ ]:
data.describe()

task_1_HOF   task_1_NOT  task_2_HATE  task_2_NONE  task_2_OFFN  \
count  4665.000000  4665.000000  4665.000000  4665.000000  4665.000000   
mean      0.529260     0.470740     0.119185     0.470740     0.144909   
std       0.499197     0.499197     0.324041     0.499197     0.352047   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       1.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     1.000000     0.000000     1.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

       task_2_PRFN  task_3_NONE   task_3_TIN   task_3_UNT  
count  4665.000000  4665.000000  4665.000000  4665.000000  
mean      0.265166     0.470740     0.331190     0.198071  
std       0.441469     0.499197     0.470692     0.398588  
min       0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000  
75%       1.000000     1.000000     1.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000

In [ ]:
data_sample = data.head(20)

In [ ]:
data_sample.head()

text_id                                               text  \
0  hasoc_hi_5556  बांग्लादेश की शानदार वापसी, भारत को 314 रन पर ...   
1  hasoc_hi_5648  सब रंडी नाच देखने मे व्यस्त जैसे ही कोई #शांती...   
2   hasoc_hi_164  तुम जैसे हरामियों के लिए बस जूतों की कमी है शु...   
3  hasoc_hi_3530  बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत ...   
4  hasoc_hi_5206  चमकी बुखार: विधानसभा परिसर में आरजेडी का प्रदर...   

   task_1_HOF  task_1_NOT  task_2_HATE  task_2_NONE  task_2_OFFN  task_2_PRFN  \
0           0           1            0            1            0            0   
1           1           0            0            0            0            1   
2           1           0            0            0            0            1   
3           0           1            0            1            0            0   
4           0           1            0            1            0            0   

   task_3_NONE  task_3_TIN  task_3_UNT  
0            1           0           0  
1            0           0           1  
2            0           1           0  
3            1           0           0  
4            1           0           0

In [ ]:


from googletrans import Translator
import random

not_trans=[]

def code_mix(text, target_language, cmi):
    # print(text)
    # translator = Translator(service_urls=['translate.googleapis.com'])
    # translated_text = translator.translate(text, src='hi', dest=target_language).text
    try:
        translator = Translator(service_urls=['translate.google.com'])
        translated_text = translator.translate(text, src='hi', dest=target_language).text
    except Exception as e:
        print(f"Error during translation: {e}")
        print(data_sample.index[data_sample['text'] == text].tolist())
        not_trans.append(data_sample.index[data_sample['text'] == text].tolist()[0])
        return text
    words = text.split()
    translated_words = translated_text.split()

    mixed_words = []
    for word, translated_word in zip(words, translated_words):
        if random.random() < cmi:
            mixed_words.append(translated_word)
        else:
            mixed_words.append(word)

    return " ".join(mixed_words)


target_language = 'en'
cmi_levels = [0.2, 0.4, 0.6]

# Create code-mixed data_sample for each CMI level
for cmi in cmi_levels:
    data_sample[f"cmi_{cmi}"] = data_sample["text"].apply(lambda x: code_mix(x, target_language, cmi))


<ipython-input-9-79caca330205>:36: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_sample[f"cmi_{cmi}"] = data_sample["text"].apply(lambda x: code_mix(x, target_language, cmi))
<ipython-input-9-79caca330205>:36: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_sample[f"cmi_{cmi}"] = data_sample["text"].apply(lambda x: code_mix(x, target_language, cmi))
<ipython-input-9-79caca330205>:36: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexe

In [ ]:
data_sample = data_sample.drop(columns=['task_2_NONE','task_3_NONE'])


In [ ]:
cols = data_sample.columns[0:7]
label_cols = ['task_1_HOF', 'task_1_NOT', 'task_2_HATE', 'task_2_OFFN', 'task_2_PRFN']

data_sample['labels'] = list(data_sample[label_cols].values)
data_sample.head()

text_id                                               text  \
0  hasoc_hi_5556  बांग्लादेश की शानदार वापसी, भारत को 314 रन पर ...   
1  hasoc_hi_5648  सब रंडी नाच देखने मे व्यस्त जैसे ही कोई #शांती...   
2   hasoc_hi_164  तुम जैसे हरामियों के लिए बस जूतों की कमी है शु...   
3  hasoc_hi_3530  बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत ...   
4  hasoc_hi_5206  चमकी बुखार: विधानसभा परिसर में आरजेडी का प्रदर...   

   task_1_HOF  task_1_NOT  task_2_HATE  task_2_OFFN  task_2_PRFN  task_3_TIN  \
0           0           1            0            0            0           0   
1           1           0            0            0            1           0   
2           1           0            0            0            1           1   
3           0           1            0            0            0           0   
4           0           1            0            0            0           0   

   task_3_UNT                                            cmi_0.2  \
0           0  बांग्लादेश की शानदार वापसी, भारत को 314 रन पर ...   
1           1    As रंडी नाच देखने मे busy जैसे ही कोई #शांतीदूत   
2           0  तुम is हरामियों के लिए बस for की कमी है शुक्र ...   
3           0  बीजेपी MLA Akash विजयवर्गीय जेल से jail, जमानत...   
4           0  चमकी बुखार: विधानसभा परिसर में the का प्रदर्शन...   

                                             cmi_0.4  \
0  बांग्लादेश की comeback, वापसी, stopped को 314 ...   
1  सब soon नाच देखने is busy watching ही कोई #शां...   
2  There जैसे a के of shoes जूतों की haravis है श...   
3  बीजेपी MLA आकाश Vijayvargiya जेल से jail, जमान...   
4  चमकी बुखार: विधानसभा परिसर में आरजेडी assembly...   

                                             cmi_0.6           labels  
0  Bangladesh's की comeback, India stopped को 314...  [0, 1, 0, 0, 0]  
1  As soon नाच someone is व्यस्त watching all कोई...  [1, 0, 0, 0, 1]  
2  There is a shortage of बस जूतों the haravis है...  [1, 0, 0, 0, 1]  
3  बीजेपी MLA Akash Vijayvargiya जेल से jail, a म...  [0, 1, 0, 0, 0]  
4  Shining बुखार: RJD परिसर in आरजेडी assembly pr...  [0, 1, 0, 0, 0]

In [ ]:
labels = data_sample.labels.values
labels

array([array([0, 1, 0, 0, 0], dtype=uint8),
       array([1, 0, 0, 0, 1], dtype=uint8),
       array([1, 0, 0, 0, 1], dtype=uint8),
       array([0, 1, 0, 0, 0], dtype=uint8),
       array([0, 1, 0, 0, 0], dtype=uint8),
       array([0, 1, 0, 0, 0], dtype=uint8),
       array([0, 1, 0, 0, 0], dtype=uint8),
       array([0, 1, 0, 0, 0], dtype=uint8),
       array([0, 1, 0, 0, 0], dtype=uint8),
       array([0, 1, 0, 0, 0], dtype=uint8),
       array([0, 1, 0, 0, 0], dtype=uint8),
       array([0, 1, 0, 0, 0], dtype=uint8),
       array([0, 1, 0, 0, 0], dtype=uint8),
       array([0, 1, 0, 0, 0], dtype=uint8),
       array([0, 1, 0, 0, 0], dtype=uint8),
       array([0, 1, 0, 0, 0], dtype=uint8),
       array([0, 1, 0, 0, 0], dtype=uint8),
       array([0, 1, 0, 0, 0], dtype=uint8),
       array([1, 0, 0, 1, 0], dtype=uint8),
       array([0, 1, 0, 0, 0], dtype=uint8)], dtype=object)

In [ ]:
data_neat = data_sample[['text_id', 'text','cmi_0.2', 'cmi_0.4', 'cmi_0.6', 'labels']]
data_neat.head()

text_id                                               text  \
0  hasoc_hi_5556  बांग्लादेश की शानदार वापसी, भारत को 314 रन पर ...   
1  hasoc_hi_5648  सब रंडी नाच देखने मे व्यस्त जैसे ही कोई #शांती...   
2   hasoc_hi_164  तुम जैसे हरामियों के लिए बस जूतों की कमी है शु...   
3  hasoc_hi_3530  बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत ...   
4  hasoc_hi_5206  चमकी बुखार: विधानसभा परिसर में आरजेडी का प्रदर...   

                                             cmi_0.2  \
0  बांग्लादेश की शानदार वापसी, भारत को 314 रन पर ...   
1    As रंडी नाच देखने मे busy जैसे ही कोई #शांतीदूत   
2  तुम is हरामियों के लिए बस for की कमी है शुक्र ...   
3  बीजेपी MLA Akash विजयवर्गीय जेल से jail, जमानत...   
4  चमकी बुखार: विधानसभा परिसर में the का प्रदर्शन...   

                                             cmi_0.4  \
0  बांग्लादेश की comeback, वापसी, stopped को 314 ...   
1  सब soon नाच देखने is busy watching ही कोई #शां...   
2  There जैसे a के of shoes जूतों की haravis है श...   
3  बीजेपी MLA आकाश Vijayvargiya जेल से jail, जमान...   
4  चमकी बुखार: विधानसभा परिसर में आरजेडी assembly...   

                                             cmi_0.6           labels  
0  Bangladesh's की comeback, India stopped को 314...  [0, 1, 0, 0, 0]  
1  As soon नाच someone is व्यस्त watching all कोई...  [1, 0, 0, 0, 1]  
2  There is a shortage of बस जूतों the haravis है...  [1, 0, 0, 0, 1]  
3  बीजेपी MLA Akash Vijayvargiya जेल से jail, a म...  [0, 1, 0, 0, 0]  
4  Shining बुखार: RJD परिसर in आरजेडी assembly pr...  [0, 1, 0, 0, 0]

In [ ]:
%pip uninstall -y accelerate
%pip install git+https://github.com/huggingface/accelerate

PS: DONT RUN THE BELOW CELL MULTIPLE TIMES WITHOUT WIPING THE COLAB VM, IT WILL RUN OUT OF DISK SPACE

In [ ]:
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from transformers import BertTokenizer, BertForSequenceClassification, TrainingArguments, Trainer
from transformers import AutoTokenizer, AutoModelForSequenceClassification
torch.cuda.empty_cache()
# Load pre-trained BERT and mBERT models and tokenizers
tokenizer_bert = BertTokenizer.from_pretrained("bert-base-multilingual-cased")
model_bert = BertForSequenceClassification.from_pretrained("bert-base-multilingual-cased", num_labels=5)

tokenizer_mbert = AutoTokenizer.from_pretrained("google/muril-base-cased")
model_mbert = AutoModelForSequenceClassification.from_pretrained("google/muril-base-cased", num_labels=5)

def encode_text(text, tokenizer, max_length=256):
    return tokenizer(text, truncation=True, max_length=max_length, padding='max_length', return_tensors='pt')

# Create a custom dataset class for the data
class CodeMixedDataset(torch.utils.data.Dataset):
    def __init__(self, texts, labels, tokenizer):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = self.texts[idx]
        label = self.labels[idx]
        label = np.argmax(label)
        encoding = encode_text(text, self.tokenizer)
        return {**{key: torch.squeeze(val, 0) for key, val in encoding.items()}, 'labels': torch.tensor(label).long()}


# Split the dataset into training and validation sets
train_data, val_data = train_test_split(data_sample, test_size=0.2)

# Create dataset objects for training and validation - 0.4
# train_dataset_4 = CodeMixedDataset(train_data["cmi_0.4"].tolist(), train_data["labels"].tolist(), tokenizer_bert)
# val_dataset_4 = CodeMixedDataset(val_data["cmi_0.4"].tolist(), val_data["labels"].tolist(), tokenizer_bert)


# # Create dataset objects for training and validation - 0.2
# train_dataset_2 = CodeMixedDataset(train_data["cmi_0.2"].tolist(), train_data["labels"].tolist(), tokenizer_bert)
# val_dataset_2 = CodeMixedDataset(val_data["cmi_0.2"].tolist(), val_data["labels"].tolist(), tokenizer_bert)


# Create dataset objects for training and validation - 0.6
train_dataset_6 = CodeMixedDataset(train_data["cmi_0.6"].tolist(), train_data["labels"].tolist(), tokenizer_bert)
val_dataset_6 = CodeMixedDataset(val_data["cmi_0.6"].tolist(), val_data["labels"].tolist(), tokenizer_bert)


# # Create dataset objects for training and validation - 0.0
# train_dataset_0 = CodeMixedDataset(train_data["text"].tolist(), train_data["labels"].tolist(), tokenizer_bert)
# val_dataset_0 = CodeMixedDataset(val_data["text"].tolist(), val_data["labels"].tolist(), tokenizer_bert)

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return {'accuracy': accuracy_score(labels, predictions)}


# Define Trainer and TrainingArguments for BERT model (will GPU run out of memory?)
training_args_bert_4 = TrainingArguments(
    output_dir='./results_bert_6',
    num_train_epochs=10,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=64,
    warmup_steps=500,
    weight_decay=0.01,
    logging_dir='./logs_bert',
    logging_steps=2,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    evaluation_strategy="epoch",
    save_strategy="epoch"
)


trainer_bert = Trainer(
    model=model_bert,
    args=training_args_bert_4,
    train_dataset=train_dataset_6,
    eval_dataset=val_dataset_6,
    compute_metrics=compute_metrics
)

# Finetune BERT model on the training data
trainer_bert.train()

# Save the finetuned BERT model
trainer_bert.save_model("./fine_tuned_bert_6")

# Clearing Cache so that colab doesnt freak out



Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertForSequenceClassification: ['cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model ch

In [ ]:
test_results = trainer_bert.evaluate(val_dataset_6)

# Print out the results
print(test_results)

{'eval_loss': 1.4921162128448486, 'eval_accuracy': 0.75, 'eval_runtime': 0.0314, 'eval_samples_per_second': 127.352, 'eval_steps_per_second': 31.838, 'epoch': 10.0}


In [ ]:
torch.cuda.empty_cache()

# Repeat the process for mBERT model and hope GPU doesnt run out of memory
# # Create dataset objects for training and validation - 0.4
# train_mdataset_4 = CodeMixedDataset(train_data["cmi_0.4"].tolist(), train_data["labels"].tolist(), tokenizer_mbert)
# val_mdataset_4 = CodeMixedDataset(val_data["cmi_0.4"].tolist(), val_data["labels"].tolist(), tokenizer_mbert)

# # Create dataset objects for training and validation - 0.2
# train_mdataset_2 = CodeMixedDataset(train_data["cmi_0.2"].tolist(), train_data["labels"].tolist(), tokenizer_mbert)
# val_mdataset_2 = CodeMixedDataset(val_data["cmi_0.2"].tolist(), val_data["labels"].tolist(), tokenizer_mbert)


# Create dataset objects for training and validation - 0.6
train_mdataset_6 = CodeMixedDataset(train_data["cmi_0.6"].tolist(), train_data["labels"].tolist(), tokenizer_mbert)
val_mdataset_6 = CodeMixedDataset(val_data["cmi_0.6"].tolist(), val_data["labels"].tolist(), tokenizer_mbert)


# # Create dataset objects for training and validation - 0.0
# train_mdataset_0 = CodeMixedDataset(train_data["text"].tolist(), train_data["labels"].tolist(), tokenizer_mbert)
# val_mdataset_0 = CodeMixedDataset(val_data["text"].tolist(), val_data["labels"].tolist(), tokenizer_mbert)

training_args_mbert_4 = TrainingArguments(
    output_dir='./results_mbert_6',
    num_train_epochs=10,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=64,
    warmup_steps=500,
    weight_decay=0.01,
    logging_dir='./logs_mbert',
    logging_steps=2,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    evaluation_strategy="epoch",
    save_strategy="epoch"
)
trainer_mbert = Trainer(
    model=model_mbert,
    args=training_args_mbert_4,
    train_dataset=train_mdataset_6,
    eval_dataset=val_mdataset_6,
    compute_metrics=compute_metrics
)

# Finetune mBERT model on the training data
trainer_mbert.train()

# Save the finetuned mBERT model
trainer_mbert.save_model("./fine_tuned_mbert_6")

/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


In [ ]:
torch.cuda.empty_cache()

In [ ]:
# Evaluate the model on the test data
test_results = trainer_mbert.evaluate(val_mdataset_6)

# Print out the results
print(test_results)


{'eval_loss': 1.6030398607254028, 'eval_accuracy': 0.75, 'eval_runtime': 0.0327, 'eval_samples_per_second': 122.456, 'eval_steps_per_second': 30.614, 'epoch': 10.0}


In [ ]:
!rm -r /content/results_bert_2/

In [ ]:
!rm -r /content/results_mbert_2/